name: azure_oauth_example
description: Demonstrates how to use the azure_oauth plugin.
publish_to: 'none'
version: 3.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  azure_oauth: 
    path: ../
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true